Update traefik.js
exoframejs/exoframe-server pull request #43
Opened 2021-04-04 20:15 UTC by FDiskas

I want to try traefik custom ports. If it will work - then we could improve this

2021-04-04 22:56 UTC, FDiskas commented
So - config would look like:
```yml
traefikPorts:
  - '7788/tcp': {}
  - '7788/udp': {}
```

2021-04-05 08:40 UTC, yamalight requested changes
A few small requests:
1. Please add tests for new feature
2. Please open issue / PR with docs on main repo

2021-04-05 08:40 UTC, yamalight commented on package.json
> +    "test": "NODE_ENV=testing jest --ci --runInBand --forceExit --coverage --silent --detectOpenHandles",
Please remove this

2021-04-05 13:03 UTC, FDiskas commented
Sorry about allot of commits - have no ability to run tests locally.

2021-04-05 17:02 UTC, yamalight approved these changes

2021-04-05 17:02 UTC, yamalight commented
Looks good, thanks!

2021-04-05 17:03 UTC, merged